dist: focal
language: cpp
addons:
  apt:
    packages:
      - build-essential

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - cd ..
  - test/test_compress.sh build/compress README.md
  - echo "C++ tests"
  - find build/ -name "*_gtest" -exec {} \;
